% Integer input
function ret = adv_intput(prompt, min, max)

  prompt = cstrcat(...
    'Enter ', ...
    prompt, ...
    ': ' ...
  );

  % Accept and validate input
  num = [];
  while isempty(num)

    tmp = str2double(input(cstrcat(prompt), "s"));
    if (tmp >= min && tmp <= max && tmp == floor(tmp))
      num = tmp;
    else
      disp(cstrcat( ...
             "Error: input must be an integer greater than or equal to", ...
             num2str(min), ...
             " and less than or equal to", ...
             num2str(max) ...
           ));
    end
  end

  ret = num;
 end
